// Renders BOARD.md from the task files' frontmatter.
//
// Derived, never hand-maintained: task files are the single source of truth,
// so a session that updates its own task cannot leave the board disagreeing
// with it.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { branches } from '../lib/git.js';
import { readTasks } from '../lib/task.js';
import { statuses } from '../lib/config.js';

// Waiting on a person first — it is the only category they can act on now.
const rank = (status, known) => {
  const meta = known[status];
  if (!meta) return 4;
  if (meta.waitsOnUser) return 0;
  if (meta.inFlight) return 1;
  if (meta.terminal) return 3;
  return 2;
};

export const render = (tasks, known, live, cfg) => {
  const ordered = [...tasks].sort((a, b) => {
    const byRank = rank(a.meta.status, known) - rank(b.meta.status, known);
    return byRank !== 0 ? byRank : a.id.localeCompare(b.id);
  });

  const out = [
    '# Board',
    '',
    'Generated by `npx crew board` — do not edit by hand.',
    'Task files are the source of truth; this is the glance view.',
    '',
    '| id | task | status | env | branch |',
    '|---|---|---|---|---|',
  ];

  for (const task of ordered) {
    const { status = '?', env = '?', branch } = task.meta;
    const shown = branch ? (live.includes(branch) ? branch : `${branch} *(gone)*`) : '—';
    const flag = known[status] ? '' : ' *(unknown)*';
    out.push(`| ${task.id} | ${task.title} | \`${status}\`${flag} | ${env} | ${shown} |`);
  }
  if (!ordered.length) out.push('| — | *no tasks yet* | | | |');

  const waiting = ordered.filter((task) => known[task.meta.status]?.waitsOnUser);
  out.push('', '## Waiting on you', '');
  if (waiting.length) {
    for (const task of waiting) {
      out.push(`- **${task.id} ${task.title}** — ${known[task.meta.status].waitsOnUser}`);
    }
  } else {
    out.push('Nothing.');
  }

  const flight = ordered.filter(
    (task) => known[task.meta.status]?.inFlight || task.meta.status === 'approved',
  );
  out.push('', '## In flight', '');
  if (flight.length) {
    for (const task of flight) {
      const rounds = task.meta.rounds > 0 ? `, round ${task.meta.rounds}/${cfg.reviewRounds}` : '';
      const where = task.meta.branch ? ` on \`${task.meta.branch}\`` : '';
      out.push(`- **${task.id} ${task.title}** — \`${task.meta.status}\`${where}${rounds}`);
    }
  } else {
    out.push('Nothing running.');
  }

  out.push('');
  return { text: out.join('\n'), waiting, total: ordered.length };
};

export const run = (cfg) => {
  const dir = join(cfg.root, cfg.tasksDir);
  const tasks = readTasks(dir);
  const known = statuses(cfg);

  const prefix = cfg.branchPrefix;
  const live = branches(cfg.root).filter((name) => !prefix || name.startsWith(prefix));

  const { text, waiting, total } = render(tasks, known, live, cfg);
  writeFileSync(join(dir, 'BOARD.md'), text);

  const unknown = tasks.filter((task) => !known[task.meta.status]);
  console.log(`board: ${total} task(s), ${waiting.length} waiting on you`);
  for (const task of unknown) {
    console.log(
      `  ${task.id}: unknown status "${task.meta.status}" — known: ${Object.keys(known).join(', ')}`,
    );
  }
  return 0;
};
